server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tedu_tea_mall
    username: root
    password: Afang19970083

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml



